version: '3.5'
services:
  api1: # API - Instância 01
    image: lazaronixon/rinha-de-backend
    hostname: api1
    depends_on:
      - db
      - cache
    expose:
      - '3000'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      CACHE_URL: redis://cache:6379/0
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
      RUBY_YJIT_ENABLE: 1
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'

  api2: # API - Instância 01
    image: lazaronixon/rinha-de-backend
    hostname: api2
    depends_on:
      - db
      - cache
    expose:
      - '3000'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      CACHE_URL: redis://cache:6379/0
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
      RUBY_YJIT_ENABLE: 1
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'

  db: # Banco de dados
   image: postgres
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
   deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'

  cache: # Redis Cache
    image: redis
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lfu
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'

  db-migrator: # Database preparation
    image: lazaronixon/rinha-de-backend
    command: bin/wait-for db:5432 -- bin/rails db:prepare
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
