version: '3.5'
services:
  api1: # API - Instância 01
    image: lazaronixon/rinha-de-backend
    hostname: api1
    depends_on:
      - db
    expose:
      - '3000'
    environment:
      RAILS_LOG_LEVEL: error
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
      RUBY_YJIT_ENABLE: 1
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '1.0GB'

  api2: # API - Instância 02
    image: lazaronixon/rinha-de-backend
    hostname: api2
    depends_on:
      - db
    expose:
      - '3000'
    environment:
      RAILS_LOG_LEVEL: error
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
      RUBY_YJIT_ENABLE: 1
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '1.0GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'

  db: # Banco de dados
   image: postgres
   command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c log_min_messages=FATAL
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
   deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.8GB'

  db-migrator: # Database preparation
    image: lazaronixon/rinha-de-backend
    command: bin/wait-for db:5432 -- bin/rails db:prepare
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha_de_backend
      RAILS_MASTER_KEY: d2066c69964ffb8b091dfddc61f42880
